language: java
os: linux
dist: bionic

jdk:
  - openjdk8
  - oraclejdk8
  - openjdk11
  - oraclejdk8

after_success:
  - mvn jacoco:report coveralls:report sonar:sonar -Dsonar.organization=$SONARCLOUD_ORG -Dsonar.host.url=$SONARCLOUD_HOST -Dsonar.login=$SONARCLOUD_TOKEN

notifications:
  email: false